server:
  port: 8080
  public-url: ${PUBLIC_URL:http://localhost:8080}

spring:
  application:
    name: payments-app

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:payments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  devtools:
    restart:
      enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password: mysecret

app:
  security:
    jwt:
      access-token-expiration: 86400000 # 1 day
      refresh-token-expiration: 604800000 # 7 days
  validation:
      disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail
webhook:
  secret: secret

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
